### ISSUE TITLE
[反馈]站点图片资源丢失

### ISSUE THREAD

**Issue by YangFong** [FEDarling/weekly-tracker#125]
**说出您的问题**
并不是链接错误，在 md 当中可以正常显示。

**截图**

![image](https://user-images.githubusercontent.com/70502828/153591740-b23335a3-b7c7-48b0-bc0a-8232aaf28108.png)

![image](https://user-images.githubusercontent.com/70502828/153591784-3ec9f33c-5092-4e4b-92b4-4255b563a6d5.png)

**提出您的建议**
无

**Comment by daodaolee** [comment]
已知晓

**Comment by KimYangOfCat** [comment]
@YangFong  感谢反馈，已修复 

[参考](https://github.com/FEDarling/weekly-tracker/commit/51e98948ec32b4b0ca213d9e6580188486eab51f)

**Comment by YangFong** [comment]
> @YangFong 感谢反馈，已修复
> 
> [参考](https://github.com/FEDarling/weekly-tracker/commit/51e98948ec32b4b0ca213d9e6580188486eab51f)

并不是只存在这一处，单此篇来说，存在三张图片，且均失效。

当然，此改动是成功的。

**Comment by KimYangOfCat** [comment]
@YangFong 
OK 我整体梳理一遍所有图片的 url，谢谢反馈
