### ISSUE TITLE
使用 RSS 订阅源无法正确进入文章详情页

### ISSUE THREAD

**Issue by zhangtuo1999** [FEDarling/weekly-tracker#258]
**说出您的问题**
使用 RSS 订阅源无法正确进入文章详情页，可能是由于 <link>元素中的 URL 多了一个斜杠。

**截图**
![捕获](https://user-images.githubusercontent.com/39889969/173371609-19564827-de52-4a7d-9f63-69b31a8bce71.PNG)

**Comment by KimYangOfCat** [comment]
已修复
