### ISSUE TITLE
JavaScript Weekly #100

### ISSUE THREAD

**Issue by daodaolee** [FEDarling/weekly-tracker#41]
## 认领说明
* 翻译前请仔细阅读 [📄 文章排版](https://github.com/FEDarling/fe-translate-weekly/wiki/%F0%9F%93%84--%E6%96%87%E7%AB%A0%E6%8E%92%E7%89%88)
* 尽量一次只领一篇，给别的小伙伴留点~

**注意：每个评论只能有一条认领，如有多条，请分开评论，保证评论数与任务数一致。**

文章有三个状态：

待认领：
- [ ] 文章标题

已认领：
- [x] 文章标题（@daodaolee）

翻译完成：
- [x] 文章标题（@daodaolee）#2

## 领取方式
从下面 **认领列表** 中选取未被人领取过的文章，在本 issues 下评论即可领取，认领文章格式如下：

```
| 标题 | 译者 | 完成时间 | PR |
| -- | -- | -- | -- |
| 文章标题 | @daodaolee | 2021.10.28 - 2021.10.30 | - |
```
示例效果：

| 标题 | 译者 | 完成时间 | PR | 
| -- | -- | -- | -- |
| 文章标题 | @daodaolee | 2022.01.22 - 2022.01.24 | - |

翻译完成后，请修改自己的认领评论，添加 PR 信息：
| 标题 | 译者 | 完成时间 | PR |
| -- | -- | -- | -- |
| 文章标题 | @daodaolee | 2022.01.22 - 2022.01.24 | #2 |

## 认领列表

- [ ] [ES2021: Here's the Features (Quickly)](https://github.com/FEDarling/fe-translate-weekly/blob/master/JavaScript_Weekly/570/ES2021_new_feature.md)（@daodaolee）
- [x] [Comparing Svelte and React](https://github.com/FEDarling/fe-translate-weekly/blob/master/JavaScript_Weekly/570/svelte_vs_react.md)（@daodaolee）
- [x] [Comparing the New Generation of Build  Tools](https://github.com/FEDarling/fe-translate-weekly/blob/master/JavaScript_Weekly/570/build_tools_compare.md)（@daodaolee）#8
- [ ] ['Rust is the Future of JavaScript Infrastructure'](https://leerob.io/blog/rust)
- [ ] [The State of Web Workers in 2021](https://javascriptweekly.com/link/118004/web)
- [ ] [Rethinking JavaScript's Ternary Operator](https://github.com/FEDarling/fe-translate-weekly/blob/master/JavaScript_Weekly/570/ternary.md)（@daodaolee）#2

**Comment by mollydl** [comment]
点个双击，摸摸哒
